markdown: rdiscount
pygments: true
auto: true
rdiscount:
  extensions: [smart]

name: "Brian Doll"
url: http://emphaticsolutions.com
description: "Maker & Marketer at GitHub"
gravatar_url: https://secure.gravatar.com/avatar/d0bd5ccf2859245b4daf49739a2ceab3

title: "Maker & Marketer at GitHub"
author:
  name: "Brian Doll"
  email: brian@emphaticsolutions.com
  github: briandoll
  twitter: briandoll
  linkedin: briandoll
  bio: "Maker & Marketer at GitHub"

BASE_PATH: /
